version: '2.1'

services:
  rtls-server:
    image: rtls-server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 7979:7979
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js